name: Runtime user Github/Azure onboard

on:
  workflow_dispatch:
    inputs:
        request-number:
          type: string
          description: "RUNTREQ number (e.g: RUNTREQ-1234)"
          required: true
        user-email:
          type: string
          description: "Email address of user"
          required: true
        user-department:
          type: choice
          description: "Department of user"
          required: true
          options:
          - AQ-121
          - AQ-631
          - AQ-632
          - BATW
          - CA-24
          - CA-614
          - CB-20
          - CB-22
          - CB-DC-4
          - CP-DC-1
          - CR-V-C-4MU
          - CR-V-D
          - CR-V-D-1
          - CTW
          - DC-2
          - DC-23
          - DE- 440
          - DE-21
          - DE-3
          - DE-3-E
          - DE-30
          - DE-301
          - DE-310
          - DE-32
          - DE-320
          - DE-321
          - DE-322
          - DE-330
          - DE-34
          - DE-341
          - DE-342
          - DE-393 
          - DE-41
          - DE-423
          - DE-43
          - DE-430
          - DE-431
          - DE-432
          - DE-44
          - DE-440
          - DE-441
          - DE-442
          - DE-443
          - DE-50
          - DE-51
          - DE-54
          - DE-540
          - DE-55
          - DE-550
          - DE-610
          - DE-612
          - DE-613
          - DE-701
          - DE-702
          - DE-72
          - DE-720
          - DE-721
          - DE-722
          - DE-73
          - DE-730
          - DE-732
          - DE-733
          - DE-791
          - DE-8
          - DE-80
          - DE-800
          - DE-801
          - DE-81
          - DE-812
          - DE-813
          - DE-82
          - DE-820
          - DE-821
          - DE-822
          - DE-823
          - DE-83
          - DE-830
          - DE-831
          - DE-833
          - DE-84
          - DE-840
          - DE-841
          - DE-85
          - DE-852
          - DE440
          - EA-911
          - EC-DE-41
          - EC-DE-43
          - EC-DE-51
          - EC-DE-64
          - EC-DE-JZ
          - EC-EE-JZ
          - EC-EE-Z
          - EE-333
          - EE-42
          - EE-440
          - EE-81
          - EE-CN
          - EE-CN-21
          - EE-CN-3
          - EE-CN-31
          - EE-CN-40
          - EE-CN-41
          - EE-CN-Z
          - EF-30
          - EG-8 BR
          - EG-8-BR
          - EG-8-KR 
          - EN-42
          - EN-51
          - EN-52
          - EN-54
          - EP-720
          - FG-153
          - FG-240
          - FG-521
          - FG-6-V-52
          - FG-6-V-53
          - FG-6-V-60
          - FG-83
          - FG-CN
          - FG-EU-ZMU
          - JC-1
          - JC-34
          - JC-7
          - JD-5
          - JD-53
          - LT-3
          - LT-6
          - PT-12T
          - PT-331
          - SF-M-20
          - SF2-US-S-52
          - SULZER
          - ZS-E-32       
        ad-invite:
          type: boolean
          description: "Azure access required"
          default: false

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
    check-details:
      runs-on: ubuntu-latest
      steps:
        - name: Check Request number
          shell: bash {0}
          run: |
            BRANCH_NAME="${{ github.event.inputs.request-number }}"
            echo $BRANCH_NAME | grep -E "^RUNTREQ-[0-9]{4}$" -q
            [ $? != 0 ] && { echo -e "\033[0;31mInvalid request\033[0m";exit 1; } || echo -e "\033[0;32mValid request\033[0m"
        
        - name: Check user email
          shell: bash {0}
          run: |
            USER_EMAIL="${{ github.event.inputs.user-email }}"
            echo $USER_EMAIL | grep -E '[[:alnum:]"[[:alnum:]%&'"'"'*+/=?`{|}~^.-]+@[[:alnum:]_-]+(\.[[:alnum:]_-]+)*\.[[:alpha:]]{2,6}' -q
            [ $? != 0 ] && { echo -e "\033[0;31mInvalid Email\033[0m";exit 1; } || echo -e "\033[0;32mValid email\033[0m"

    perform-action:
      needs: check-details
      runs-on: ubuntu-latest
      steps:        
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.8'
        
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            path: repo

        - name: Check email already used
          working-directory: repo
          shell: bash {0}
          run: |
            USER_EMAIL="${{ github.event.inputs.user-email }}"
            echo "Email to check in file $USER_EMAIL"
            grep -qi $USER_EMAIL ./example.tf 
            [ $? = 0 ] && { echo -e "\033[0;31mEmail alreay configured\033[0m";exit 1; } || echo -e "\033[0;32mGoinf Forward\033[0m"

        - name: Install requirements
          run: pip install -r ./.ci/onboard/requirements.txt
          working-directory: repo

        - name: Executing script
          working-directory: repo
          run: |
            echo "Performing action: ${{ github.event.inputs.request-number }} ${{ github.event.inputs.user-email }} ${{ github.event.inputs.user-department }} ${{ github.event.inputs.ad-invite }}"
            if [ ${{ github.event.inputs.ad-invite }} ]
            then
              python3 ./.ci/onboard/app.py -m ${{ github.event.inputs.user-email }} -d ${{ github.event.inputs.user-department }} --Azure
            else
              python3 ./.ci/onboard/app.py -m ${{ github.event.inputs.user-email }} -d ${{ github.event.inputs.user-department }}
            fi
        
        - name: Commit changes for new user
          working-directory: repo
          run: |
            git checkout -b ${{ github.event.inputs.request-number }}
            git add .
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "[${{ github.event.inputs.request-number }}] : Onboard new user"
            git push --set-upstream origin ${{ github.event.inputs.request-number }}

        - name: Get a GitHub app token to give this action access to our repo
          id: get_token
          uses: getsentry/action-github-app-token@v2.0.0
          with:
            private_key: ${{ secrets.CODE_BOT_APP_PEM }}
            app_id: ${{ secrets.CODE_BOT_APP_ID }}

        - name: Create pull request
          working-directory: repo
          run: |
            echo "token ${{ steps.get_token.outputs.token }}"
            gh pr create -B 'main' -H ${{ github.event.inputs.request-number }} --title '[${{ github.event.inputs.request-number }}] : Onboard new user' --body 'Created by Github action 💪'
          env:
            GH_TOKEN: ${{ steps.get_token.outputs.token }}
            GH_HOST: "github.com"
